apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-deployment
  labels:
    app: aws

spec:
  replicas: 2

  selector:
    matchLabels:
      app: aws

  template:
    metadata:
      labels:
        app: aws

    spec:
      containers:
        - name: aws
          image: 835175800251.dkr.ecr.us-east-1.amazonaws.com/aws:cadd415d56f697b40691e70e963448fd1cd62b86
          imagePullPolicy: Always

          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service

metadata:
  name: aws-service

spec:
  selector:
    app: aws

  ports:
    - port: 80
      targetPort: 80

  type: ClusterIP
