apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-deployment
  labels: { app: azure }
spec:
  replicas: 2
  selector:
    matchLabels: { app: azure }
  template:
    metadata:
      labels: { app: azure }
    spec:
      containers:
        - name: azure
          image: 851725468573.dkr.ecr.us-east-1.amazonaws.com/azure:4d9a97e86b1b4082574b088a991d1b444e18393e
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: azure-service
spec:
  selector: { app: azure }
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

#
